services:
  postgres:
    image: postgres:15
    container_name: iswprueba-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: plataforma
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d plataforma"]
      interval: 5s
      timeout: 5s
      retries: 20
    restart: unless-stopped

  adminer:
    image: adminer
    container_name: iswprueba-adminer
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: iswprueba-backend
    environment:
      DB_USER: user
      DB_PASSWORD: pass
      DB_NAME: plataforma
      DB_HOST: postgres
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "5000:5000"
    volumes:
      - ./backend/uploads:/usr/src/app/uploads
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: iswprueba-frontend
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - REACT_APP_API_BASE=http://localhost:5000
      - FAST_REFRESH=true
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app # Monta todo el directorio frontend
      - /app/node_modules # Evita sobrescribir node_modules
    stdin_open: true # Habilita stdin
    tty: true # Habilita TTY
    command: npm start # Sobrescribe el CMD del Dockerfile
    restart: unless-stopped

volumes:
  pg_data:
